services:
  - type: web
    name: plato-auto
    env: python
    buildCommand: bash render-build.sh
    startCommand: python app.py
    plan: free
    envVars:
      - key: TEST_USER_ID
        value: your_id
      - key: TEST_USER_PW
        value: your_password
